name: Merge to Main

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Node sample
        steps:
            - uses: actions/checkout@v3
            - name: Run linting rules and tests
              run: |
                npm ci
                npm run lint
                npm run test
            - run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ Secrets.NPMJS }}